version:  '3.2'

services:

  redis:
    image: "redis:latest"
    networks:
      - javanet
    ports:
      - 6379:6379

  mongo:
    image: "mongo:latest"
    networks:
      - javanet
    ports:
      - 27017:27017

networks:
  javanet:
